package main

const (
	daoHeader = `// Code generated by gormer. DO NOT EDIT.
package %s

import (
	"context"
	"time"
	
	"github.com/pkg/errors"
	"gorm.io/gorm"
	
	"%s/%s"
)
`
	daoExtHeader = `package %s

	// write you method here
`

	daoExtTmpl = `
type %sExtModel interface {

}
`
)

var (
	daoTmplRepo = `
type {{.StructName}}Repo struct {
	db *gorm.DB
}

func New{{.StructName}}Repo(db *gorm.DB) *{{.StructName}}Repo {
	return &{{.StructName}}Repo{db: db}
}

var _ {{.StructName}}Model = New{{.StructName}}Repo(nil)

type {{.StructName}}Model interface {
	Add{{.StructName}}(ctx context.Context, {{.StructSmallCamelName}} *model.{{.StructName}}) (err error)
	Query{{.StructName}}s(ctx context.Context, pageNumber, pageSize int, condition *model.{{.StructName}}Options) ({{.StructSmallCamelName}}s []model.{{.StructName}}, err error)
	Count{{.StructName}}s(ctx context.Context, condition *model.{{.StructName}}Options) (count int64, err error)
	Update{{.StructName}}(ctx context.Context, updated, condition *model.{{.StructName}}Options) (err error)
	Delete{{.StructName}}(ctx context.Context, condition *model.{{.StructName}}Options) (err error)
	
	{{.StructName}}ExtModel
}

`
	daoTmplAdd = `func (repo *{{.StructName}}Repo) Add{{.StructName}}(ctx context.Context, {{.StructSmallCamelName}} *model.{{.StructName}}) (err error) {
{{if ne .FieldCreateTime "" }}
    if {{.StructSmallCamelName}}.{{.FieldCreateTime}}.IsZero() {
		{{.StructSmallCamelName}}.{{.FieldCreateTime}} = time.Now()
	}{{end}}
{{if ne .FieldUpdateTime "" }}
    if {{.StructSmallCamelName}}.{{.FieldUpdateTime}}.IsZero() {
		{{.StructSmallCamelName}}.{{.FieldUpdateTime}} = time.Now()
	}{{end}}
	repo.db.WithContext(ctx).
		Table(model.{{.StructName}}TableName).
		Create({{.StructSmallCamelName}})
	err = repo.db.Error
	return
}

`
	daoTmplQuery = `func (repo *{{.StructName}}Repo) Query{{.StructName}}s(ctx context.Context, pageNumber, pageSize int, condition *model.{{.StructName}}Options) ({{.StructSmallCamelName}}s []model.{{.StructName}}, err error) {
	db := repo.db
	if condition != nil {
		db = db.Where(condition.{{.StructName}}, condition.Fields)
	}
{{if ne .FieldSoftDeleteKey "" }}
	db = db.Where("{{.TableSoftDeleteKey}} != ?", {{.TableSoftDeleteValue}})
{{ end }}
	db.WithContext(ctx).
		Table(model.{{.StructName}}TableName).
		Limit(pageSize).
		Offset((pageNumber - 1) * pageSize).
		Find(&{{.StructSmallCamelName}}s)
	err = repo.db.Error
	return
}

`
	daoTmplCount = `func (repo *{{.StructName}}Repo) Count{{.StructName}}s(ctx context.Context, condition *model.{{.StructName}}Options) (count int64, err error) {
	db := repo.db
	if condition != nil {
		db = db.Where(condition.{{.StructName}}, condition.Fields)
	}
{{if ne .FieldSoftDeleteKey "" }}
	db = db.Where("{{.TableSoftDeleteKey}} != ?", {{.TableSoftDeleteValue}})
{{ end }}
	db.WithContext(ctx).
		Table(model.{{.StructName}}TableName).
		Count(&count)
	err = repo.db.Error
	return
}

`
	daoTmplUpdate = `func (repo *{{.StructName}}Repo) Update{{.StructName}}(ctx context.Context, updated, condition *model.{{.StructName}}Options) (err error) {
	if updated == nil || len(updated.Fields) == 0 {
		return errors.New("update must choose certain fields")
	} else if condition == nil {
		return errors.New("update must include where condition")
	}
{{if ne .FieldUpdateTime "" }}
    if updated.{{.StructName}}.{{.FieldUpdateTime}}.IsZero() {
		updated.{{.StructName}}.{{.FieldUpdateTime}} = time.Now()
		updated.Fields = append(updated.Fields, "{{.TableUpdateTime}}")
	}
{{end}}
	repo.db.WithContext(ctx).
		Table(model.{{.StructName}}TableName).
		Where(condition.{{.StructName}}, condition.Fields).
		Select(updated.Fields).
		Updates(updated.{{.StructName}})
	err = repo.db.Error
	return
}

`
	daoTmplDelete = `func (repo *{{.StructName}}Repo) Delete{{.StructName}}(ctx context.Context, condition *model.{{.StructName}}Options) (err error) {
	if condition == nil {
		return errors.New("delete must include where condition")
	}

	repo.db.WithContext(ctx).
        Table(model.{{.StructName}}TableName).
		Where(condition.{{.StructName}}, condition.Fields).
{{if eq .FieldSoftDeleteKey "" }} Delete(&model.{{.StructName}}{})
{{ else }}  {{if eq .FieldUpdateTime "" }}
	Select("{{.TableSoftDeleteKey}}").
	Updates(&model.{{.StructName}}{
		{{.FieldSoftDeleteKey}}:{{.TableSoftDeleteValue}},
	})
{{ else }}
		Select("{{.TableSoftDeleteKey}}","{{.TableUpdateTime}}").
		Updates(&model.{{.StructName}}{
			{{.FieldSoftDeleteKey}}:{{.TableSoftDeleteValue}},
			{{.FieldUpdateTime}} : time.Now(),
		}){{ end }}{{ end }}
	err = repo.db.Error
	return
}

`
	daoTmpl = daoTmplRepo + daoTmplAdd + daoTmplQuery + daoTmplCount + daoTmplUpdate + daoTmplDelete
)
